apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
spec:
  containers:
    - image: yinzige/kubia
      name: kubia-container-name
      ports:
        - containerPort: 8080
          protocol: TCP