apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-v2
  labels:
    creation_mrthod: manual
    env: prod
spec:
  containers:
    - image: yinzige/kubia
      name: kubia-container-name
      ports:
        - containerPort: 8080
          protocol: TCP