apiVersion: v1
kind: Pod
metadata:
  name: downward-volume-pod
  labels:
    is_ready: "ok"
  annotations:
    key1: VALUE1
    key2: |
      VALUE2
      VALUE20
      VALUE200
spec:
  containers:
    - name: main
      image: busybox
      command:
        - "sleep"
        - "1000"
      volumeMounts:
        - mountPath: /etc/downward
          name: downward
  volumes:
    - name: downward
      downwardAPI:
        items:
          - path: "pod_labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "pod_annotations"
            fieldRef:
              fieldPath: metadata.annotations
          - path: "container_request_memory"
            resourceFieldRef:
              containerName: main
              resource: requests.cpu
              divisor: 1m
