apiVersion: v1
kind: Pod
metadata:
  name: kubia-unhealthy-v2
spec:
  containers:
    - image: yinzige/kubia-unhealthy
      name: kubia
      livenessProbe:
        httpGet:
          path: '/'
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 10
